version: "2.4"

services:
  db:
    image: postgres:12-alpine3.15
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend


  api:
    build: 
      context: ./lib_catalog
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - "db:database"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend


  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile.3task
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - frontend


networks:
  frontend:
  backend:
